### PR TITLE
remove pipeline v1 code for AODN NSW OEH

### PR DESCRIPTION
**Pull request by lbesnard**
@mhidas this will have to be merged once we're ready.
Also a manual step will have to be done by @lwgordonimos to remove the pipeline 1 from celery

### CODE REVIEW

**Comment by lbesnard** [comment]
@mhidas FYI, this has to be merged as well.

**Comment by mhidas** [comment]
Yep, thanks for the reminder!

**Comment by lbesnard** [comment]
all good! we will have to get the pipeline removed from celery as well manually with @lwgordonimos

**Comment by mhidas** [comment]
I've just run data_services_prod_merge on Jenkins, so this will be on prod next time it's provisioned.

**Pull request merged**
