### PR TITLE
SOOP XBT - parse keys netcdf

### PR DESCRIPTION
**Pull request by lbesnard**
@BecCowley for you to review. I'll keep adding commits in this draft PR. Feel free to comment along the way

### CODE REVIEW

**Comment by BecCowley** [comment]
@lbesnard, thanks. It looks ok so far. I think when you've got something ready to test, let me know and I can review in detail.

**Comment by lbesnard** [comment]
@BecCowley  this version is a working one.

I have tested against the old CSIRO2018 dataset I had, as well as the new GTSPPmer2017 set you sent me.
You now have to run the script against the root folder of a campaign containing the *_keys.nc file
such as 
```
./xbt_dm_imos_conversion.py -i ~/Documents/Work/IMOS/SOOP/XBT/GTSPPmer2017/ -o /tmp/xbt
```

I haven't incorporated yet the changes you added in your branch which take into account the fall rate.
I'm not working tomorrow, so this will have to wait until Monday!

**Comment by BecCowley** [comment]
@lbesnard, thanks. I will take a look tomorrow if I can!

**Comment by BecCowley** [comment]
@lbesnard, one immediate issue I have come across with the calling of the routine is that the *_keys.nc file is located at the same level as the folder containing all the netcdf files. And typically, I have multiple databases, therefore multiple *_keys.nc files under the same folder.
You would need to look for the matching *_keys.nc file at the same level as the input call.

Eg for the example you give above, the data files sit under this folder:
~/Documents/Work/IMOS/SOOP/XBT/GTSPPmer2017/

The keys file sits here:
~/Documents/Work/IMOS/SOOP/XBT/GTSPPmer2017_keys.nc

For testing, I can move the keys file for now.

**Comment by lbesnard** [comment]
@BecCowley This is "fixed" in the last commit. 
you can call the script either way
```bash
    ./xbt_dm_imos_conversion.py -i XBT/GTSPPmer2017/GTSPPmer2017MQNC_keys.nc -o /tmp/xb
    ./xbt_dm_imos_conversion.py -i XBT/GTSPPmer2017/GTSPPmer2017MQNC -o /tmp/xb
```

**Comment by lbesnard** [comment]
@BecCowley 
let me know what you would like to add/modify in the code. I'm not sure what you want to do with the files you uploaded on your branch:
* WMO1770.txt 
* WMO4770.txt 
* fallratecoeffs.txt

**Comment by BecCowley** [comment]
@lbesnard , I put them there initially as separate tables to read in as needed. However, I ended up putting the information in the xbt_config file. I guess we can keep them as reference or remove them. I think for one of the tables, I only put relevant parts in the xbt_config file, not all of the information.

**Comment by BecCowley** [comment]
@lbesnard. Here are some more modifications required:

- Move the history global attribute to the HISTORIES variable set.
Specify the XBT_recorder_type in the global attributes (use the xbt_config file to figure out which recorder it is)
- Specify the XBT_probetype_fallrate_equation a and b values using the xbt_config file. This might be tricky as the early *raw.nc files might have a different fall rate equation than the *ed.nc files. Do we put the fall rate coefficients in the DEPTH and DEPTH_ADJUSTED attributes or put two global attributes (one for DEPTH and one for DEPTH_ADJUSTED)?
- The XBT_input_filename doesn't have the database name at the start of the file path.
- Add DEPTH_quality_control and TEMPERATURE_quality_control variables and use the QC values in the *raw.nc file.
- When a 'PE' flag is present in the Act_Code, the latitude and longitude qc flags need to be adjusted. Hopefully the Q_Pos flag indicates the quality has changed from 1 to 2. Need to check our files as we come across the PE flags.
- Change 'source_id' label to 'gts_insertion_node'
- Change 'precision' label to 'gtspp_precision_code'
- Change 'digitisation_code' label to 'gtspp_digitisation_method_code'
- Can we group the global attributes so that all the serial numbers, crc, precisions etc are together and post/predrop_comments are together. Minor thing, but makes it a bit easier to read. I can come up with an order for you.

Suggested Histories set:
Dimensioned by N_HISTORY (probably unlimited?) and string_n dimensions:
        char HISTORY_INSTITUTION(N_HISTORY, STRING4) ;
                HISTORY_INSTITUTION:long_name = "Institution which performed action" ;
                HISTORY_INSTITUTION:Conventions = "GTSPP IDENT_CODE table" ;
        char HISTORY_STEP(N_HISTORY, STRING4) ;
                HISTORY_STEP:long_name = "Step in data processing" ;
                HISTORY_STEP:Conventions = "GTSPP PRC_CODE table" ;
        char HISTORY_SOFTWARE(N_HISTORY, STRING16) ;
                HISTORY_SOFTWARE:long_name = "Name of software which performed action" ;
                HISTORY_SOFTWARE:Conventions = "Institution dependent" ;
        char HISTORY_SOFTWARE_RELEASE(N_HISTORY, STRING16) ;
                HISTORY_SOFTWARE_RELEASE:long_name = "Version/Release of software which performed action" ;
                HISTORY_SOFTWARE_RELEASE:Conventions = "Institution dependent" ;
        char HISTORY_DATE(N_HISTORY, DATE_TIME) ;
                HISTORY_DATE:long_name = "Date the history record was created" ;
                HISTORY_DATE:Conventions = "yyyymmddHHMMSS" ;
        char HISTORY_PARAMETER(N_HISTORY, STRING16) ;
                HISTORY_PARAMETER:long_name = "Parameter that action is performed on" ;
                HISTORY_PARAMETER:Conventions = "GTSPP PC_PROF table" ;
        float HISTORY_START_DEPTH(N_HISTORY) ;
                HISTORY_START_DEPTH:long_name = "Start depth action applied to" ;
                HISTORY_START_DEPTH:Conventions = "m" ;
        float HISTORY_STOP_DEPTH(N_HISTORY) ;
                HISTORY_STOP_DEPTH:long_name = "End depth action applied to" ;
                HISTORY_STOP_DEPTH:Conventions = "m" ;
        float HISTORY_PREVIOUS_VALUE(N_HISTORY) ;
                HISTORY_PREVIOUS_VALUE:long_name = "Parameter/Flag previous value before action" ;
                HISTORY_PREVIOUS_VALUE:Conventions = "" ;
        char HISTORY_QCTEST(N_HISTORY, STRING2) ;
                HISTORY_QCTEST:long_name = "QC test performed" ;
                HISTORY_QCTEST:Conventions = "GTSPP ACT_CODE table and CSIRO XBT Cookbook" ;

**Comment by lbesnard** [comment]
>     * Add DEPTH_quality_control and TEMPERATURE_quality_control variables and use the QC values in the *raw.nc file.
@BecCowley  I'm very confused by this. I assumed that the raw data was not QC'd. and that the edited data was QC'd and with adjusted values

**Comment by BecCowley** [comment]
@lbesnard, you are correct. The raw data isn't QC'd. But, we should have a qc field in there. Generally it will always be filled with zeros (not qc'd).
However, I can think of two possible times we will have flags in there:
1. When we fully implement a real-time qc process. At the moment, the Turo software has an autoQC in place and those flags are not recorded in the current system, but we are transitioning to BUFR transmission and these flags will be carried.
2. when we get data from other users that has some QC on it and we want to retain their QC, but perhaps add or do our own.

**Comment by lbesnard** [comment]
>     * When a 'PE' flag is present in the Act_Code, the latitude and longitude qc flags need to be adjusted. Hopefully the Q_Pos flag indicates the quality has changed from 1 to 2. Need to check our files as we come across the PE flags.

could you give more precision on this, please? Should ALL the lat and lon qc values be adjusted? or only some values ?

**Comment by lbesnard** [comment]
s

> > ```
> > * When a 'PE' flag is present in the Act_Code, the latitude and longitude qc flags need to be adjusted. Hopefully the Q_Pos flag indicates the quality has changed from 1 to 2. Need to check our files as we come across the PE flags.
> > ```
> 
> 
> could you give more precision on this, please? Should ALL the lat and lon qc values be adjusted? or only some values ?

sorry my bad, it's only one value !! I didn't think. However should this be modified to a value of '2'?

**Comment by BecCowley** [comment]
@lbesnard, at this stage, set the lat/long position to whatever is in the 'Q_Pos' field in the old files. I will search for a PE flag and check that the Q_Pos has been altered to '2'. If it hasn't, we need to consider putting the quality to 2 in the code.

**Comment by lbesnard** [comment]
>     * Specify the XBT_probetype_fallrate_equation a and b values using the xbt_config file. This might be tricky as the early *raw.nc files might have a different fall rate equation than the *ed.nc files. Do we put the fall rate coefficients in the DEPTH and DEPTH_ADJUSTED attributes or put two global attributes (one for DEPTH and one for DEPTH_ADJUSTED)?

I'm adding the coef as attribute in each variable. If the coef are different for both raw and ed, we probably need to create a [FRE_RAW] and [FRE_ED] category in the xbt_config file. Will need to adjust the code lightly

**Comment by lbesnard** [comment]
I can do something quite similar for XBT_recorder_type which currently says to look into the WMO4770 file. should I just replace the XBT_recorder_type value with what I find in this file?

**Comment by BecCowley** [comment]
Yes, that was what I was thinking.

**Comment by lbesnard** [comment]
> Move the history global attribute to the HISTORIES variable set.

Is there any reason why these various history variables should exist? Are they required by some sort of software?
I'm asking this as I always find this format really old school, and hard to use/read because of the various characters.
I would much rather create respective global attributes. What do you thing?

**Comment by BecCowley** [comment]
@lbesnard, I am open to ideas on this. I would like to use the new format to QC our XBT data (replacing the current not-nice format). We would use our Mquest matlab GUI to interact directly with these files.

That means, I need to easily see/read the QC flags if we do a ncdump, and in Mquest, easily interact with the history information and associated values.
If we keep the QC flagging in the global attributes, it is ok to handle programatically, but will need parsing when QC is performed which could be a bit tedious to program. It is also difficult to read quickly when checking what is in the file.

Are there other options for storing the flags and information in variables that you know of?

**Comment by lbesnard** [comment]
@BecCowley yes sorry, I guess I misunderstood the pupose of the HISTORY set. It was clearer when I started working on it. I added the changes. Let me know how it works for you

**Comment by lbesnard** [comment]
a few things need to be modified such as the values of the following variables:
* HISTORY_INSTITUTION
* HISTORY_SOFTWARE
* HISTORY_START_DEPTH
* HISTORY_STOP_DEPTH

**Comment by lbesnard** [comment]
@BecCowley let me know if all those different changes are working for you. cheers

**Comment by BecCowley** [comment]
@lbesnard, this is looking great. Here are a few things I hope you can have a look at:

Global attributes
- XBT_probetype_fallrate_equation and XBT_recorder_type: can we include the code and the value for both these. Eg: 
**XBT_recorder_type**: WMO Code table 4770 code 72 "TURO/CSIRO Quoll XBT acquisition system"
**XBT_probetype_fallrate_equation**: WMO Code Table 1770 code 052 "a=6.691,b=-2.25"

- For instances where the *raw .nc file has a different fall rate equation - we need to figure out how to handle that. Should we make a new global attribute eg: XBT_probetype_fallrate_equation_DEPTH and XBT_probetype_fallrate_equation_DEPTH_ADJUSTED?

History section:
I would like to finesse this section a bit, but it might take a little bit of use to figure out exactly the best way it should be formatted. For now, if you are able to do these changes, I can work with it and edit the code myself as I use it.

- HISTORY_STOP_DEPTH: At the moment, the values are the same as the start point. But, really they should be different for some of the flags. Eg, wire break starts at the value in the old file version, but goes to the end of the profile. The HISTORY_STOP_DEPTH should be the final depth in the profile. There are other flags that require a similar HISTORY_STOP_DEPTH - but their stop depth will be the depth before the next flag, or the deepest depth if there is no next flag. Eg: LE or WS. If you could code one of these examples, I can probably deal with the rest. Or, I can make a full list of which flags need a different stop depth and what the logic is?

- HISTORY_SOFTWARE - I do know mostly which softwares were used for QC. It looks like I can edit the value in the code before I run it over our files. Is there another way to make the value editable?

-HISTORY_PREVIOUS_VALUE: I would like to restore the temperature values that are associated with the 'CS' (surface spike removed) flag. That means identifying them, putting them back into the TEMP_ADJUSTED field, then putting a flag of 3 (probably bad) on them. The values can also stay in the HISTORY_PREVIOUS_VALUE field. This process would need to apply to both the TEMP_ADJUSTED and TEMP (from the *raw.nc file). 

If the *raw.nc file has existing flags, it raises more questions about how we move the flag information into the history section of the new files. I have to think on this and maybe wait till we run into the issue. Any ideas are welcome!

**Comment by lbesnard** [comment]
@BecCowley I think I have covered all your requests. But the last two commits are only attempts at it.

**Comment by BecCowley** [comment]
@lbesnard, thanks. I've run it and found this small thing you might be able to fix quickly:

- XBT_probetype_fallrate_equation global attribute can be removed (we now have the DEPTH and DEPTH_ADJUSTED versions).
- Can we put the XBT_probetype_fallrate_equation_DEPTH and XBT_probetype_fallrate_equation_DEPTH_ADJUSTED attributes next to each other in the file?

I can see that the last two commits are not quite right, but thanks for getting them in place. I can have a go at fixing them myself.

Thanks so much for doing this!

**Comment by lbesnard** [comment]
@BecCowley I added some of the changes you wanted

**Comment by BecCowley** [comment]
@lbesnard thanks, looks good.
Do you want to leave this branch open so I can fix the final parts, or merge and I can start another one?

**Comment by lbesnard** [comment]
I have the feeling it might be easier to merge this one, and you can start another one.

**Pull request merged**
