### PR TITLE
feat(decomission): rm AATAMS_NRT watcher & handler

### PR DESCRIPTION
**Pull request by ocehugo**
Related to https://github.com/aodn/chef-private/pull/3446

### CODE REVIEW

**Comment by bpasquer** [comment]
@ocehugo  you can delete all AATAMS nrt related code

**Comment by lbesnard** [comment]
> @ocehugo you can delete all AATAMS nrt related code

are we sure of this, or do we simply want to disable to pipeline v1? There is still a cron job downloading the files

cron.d/AATAMS_SATTAG_NRT
AATAMS/AATAMS_sattag_nrt/aatams_nrt.py

**Comment by bpasquer** [comment]
Actually, @lbesnard  mentioned also files in the WIP directory . So he's going to finish the clean up

**Comment by ocehugo** [comment]
@bpasquer 
I agree but I just followed other decommissions style. If you look into other folders there are still files remaining (python,readmes,etc).

**Comment by ocehugo** [comment]
I forgot about the cron jobs.

**Pull request merged**
