### PR TITLE
feat(decomission): ANMN_PA watcher removal

### PR DESCRIPTION
**Pull request by ocehugo**
See also https://github.com/aodn/chef-private/pull/3395

### CODE REVIEW

**Comment by mhidas** [comment]
You might as well remove the handler script (https://github.com/aodn/data-services/blob/master/ANMN/acoustic/incoming_handler.sh) in this PR too, as it is now obsolete. (Leave the other code in that directory, as it is still needed).

**Comment by ocehugo** [comment]
@mhidas,

I just renamed the incoming_handler so we don't need to lose the code if we ever need to re-run.

**Comment by mhidas** [comment]
We won't lose the code because it's in github!

**Comment by ocehugo** [comment]
done

**Comment by mhidas** [comment]
@lwgordonimos When you have a minute, could you please use your super-powers to shut down the ANMN_PA pipeline on 10-aws-syd (and 4-nec-hob)?

**Pull request merged**
