### PR TITLE
SOOP XBT DM - python3 conversion

### PR DESCRIPTION
**Pull request by lbesnard**
@BecCowley I've updated the code to be compatible with python3. I've tested it thoroughly but the changes are quite involved, so it would be good if you could please compare a new NetCDF generated with this code with the previous version as well. I probably should add some unit testing so we can make sure in the future code changes aren't modifying NetCDF files in an unwanted way.

Regarding your python3 question, I would recommend installing conda, anaconda3


```bash
CONDA=$HOME/anaconda3
DATA_SERVICES_DIR=[location of the repo[
conda create -y -n data-services_3.5 python=3.5                                                                                                                                                                                                                                    
conda activate data-services_3.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
$CONDA/env/data-services_3.5/bin/pip install -r $DATA_SERVICES_DIR/requirements.txt                                                                                                                                                                                                                                
```

you will then be able to activate the conda environment any time you need to do some xbt dm processing.

Let me know if something is not clear.

cheers

### CODE REVIEW

**Comment by BecCowley** [comment]
@lbesnard , I followed your setup instructions for anaconda 3. It would be good to update the readme file to reflect the use of the Anaconda environment rather than the workon.
The requirements.txt has an old version  of scipy listed and it caused an error when I ran the final command. I have managed to run the code and make some netcdf files, though, using the scipy version 1.4.1
Here are the edited commands I used for the Anaconda3 installation:

CONDA=$HOME/anaconda3**/opt**
DATA_SERVICES_DIR=[location of the repo[
conda create -y -n data-services_3.5 python=3.5                                                                                                                                                                                                                                    
conda activate data-services_3.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
$CONDA/**envs**/data-services_3.5/bin/pip install -r $DATA_SERVICES_DIR/requirements.txt

**Comment by BecCowley** [comment]
@lbesnard, I checked the netcdf files created and found these things:

Extra characters in the serial number and uniqueid fields ('LL'):
XBT_instrument_serialnumber = 1237600LL
XBT_uniqueid = 89012483LL

We need to make the inputfile name include the entire database name and path to the file:
XBT_input_filename = "83ed.nc"
should be: "CSIROXBT2020ant/89/01/24/83ed.nc"

geospatial_vertical_max & min global attributes contain every depth. 

We should have flags of '1' on the lat/long, as these have been QC'd. Although not explicit in the original netcdf files.

As discussed, I'd like to try updating the netcdf format anyway. We can talk about that soon hopefully.

**Comment by lbesnard** [comment]
> Extra characters in the serial number and uniqueid fields ('LL'):

HI @BecCowley , the LL in the ncdump only means the type is long


I'll have a look at the other issues!

**Comment by lbesnard** [comment]
@BecCowley a lot of changes in those commits above

1) please have a look at this https://github.com/aodn/data-services/pull/990
This is another PR which is not merged it. But I generate my conda environment like this now, and it seems to be working fine
2) I fixed all the issues you mentioned above, as well as adding a unittest file. I believe this will give us confidence in the future that code changes don't add unexpected issues in the NetCDF files

you can run the test file like this

```bash
./test_xbt_dm_imos_conversion.py
INFO:imos_logging:Parsing ./test/CSIRO2018/CSIROXBT2018/89/00/97/78ed.nc
INFO:imos_logging:Creating output /tmp/tmp_yjntib2/IMOS_SOOP-XBT_T_20180314T091400Z_PX34_FV01_ID-89009778.nc
.INFO:imos_logging:Parsing ./test/CSIRO2018/CSIROXBT2018/89/00/97/78ed.nc
.
----------------------------------------------------------------------
Ran 2 tests in 1.981s

OK
```

**Comment by BecCowley** [comment]
@lbesnard, I've tested the code. Output looks fine, except for:
:XBT_input_filename = "/89/01/25/05ed.nc" ;

Is still missing the database folder name at the start (one folder higher). It will help with traceability at our end if we have to go back and find a file.

Also tried the #990, but didn't have much success. I got an error when I tried to run it. So I used my existing environment. Error is:

DELAYED cow074$ conda env create -f environment.yml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 80, in execute
        directory=os.getcwd())
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 40, in detect
        if spec.can_handle():
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 151, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 136, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 101, in compose_document
        node = self.compose_node(None, None)
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 138, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 211, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 141, in check_event
        self.current_event = self.state()
      File "/Users/cow074/opt/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 719, in parse_flow_mapping_key
        token.start_mark,
    ruamel_yaml.parser.ParserError: while parsing a flow mapping
      in "<unicode string>", line 1, column 1:
        {\rtf1\ansi\ansicpg1252\cocoartf ... 
        ^ (line: 1)
    expected ',' or '}', but got '{'
      in "<unicode string>", line 2, column 1:
        {\fonttbl\f0\fmodern\fcharset0 C ... 
        ^ (line: 2)

`$ /Users/cow074/opt/anaconda3/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/cow074/opt/anaconda3/bin/conda
             CONDA_PREFIX=/Users/cow074/opt/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/cow074/opt/anaconda3/bin/python
               CONDA_ROOT=/Users/cow074/opt/anaconda3
              CONDA_SHLVL=1
                 GEM_PATH=/Users/cow074/.rvm/gems/ruby-2.4.2:/Users/cow074/.rvm/gems/ruby-2.4.2@
                          global
                     PATH=/Users/cow074/opt/anaconda3/bin:/Users/cow074/opt/anaconda3/bin:/Users
                          /cow074/opt/anaconda3/condabin:/Users/cow074/.rvm/gems/ruby-2.4.2/bin:
                          /Users/cow074/.rvm/gems/ruby-2.4.2@global/bin:/Users/cow074/.rvm/rubie
                          s/ruby-2.4.2/bin:/Users/cow074/opt/anaconda3/bin:/opt/local/bin:/opt/l
                          ocal/sbin:/Users/cow074/opt/anaconda3/bin:/Users/cow074/opt/anaconda3/
                          bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/b
                          in:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/laps:/usr/local/munki:/opt
                          /X11/bin:/Users/cow074/.xbt_processing/data-
                          services/SOOP/SOOP_XBT/DELAYED:/Users/cow074/.rvm/bin
               PYTHONPATH=:/Users/cow074/.xbt_processing/data-services/lib/python
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
             rvm_bin_path=/Users/cow074/.rvm/bin
                 rvm_path=/Users/cow074/.rvm

     active environment : base
    active env location : /Users/cow074/opt/anaconda3
            shell level : 1
       user config file : /Users/cow074/.condarc
 populated config files : /Users/cow074/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/cow074/opt/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cow074/opt/anaconda3/pkgs
                          /Users/cow074/.conda/pkgs
       envs directories : /Users/cow074/opt/anaconda3/envs
                          /Users/cow074/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 69489:515598196
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: N

**Comment by BecCowley** [comment]
@lbesnard, I had an error when trying to convert a file that has a QC of 2 on the DEPTH values. I will email you the file. We need to make sure depth flags are also transferred to the IMOS format files.

Here is the error:

INFO:imos_logging:Parsing /Volumes/UOT-data/quest/BOM/BOM2019/15/77/86ed.nc
Traceback (most recent call last):
  File "/Users/cow074/xbt_processing/data-services/SOOP/SOOP_XBT/DELAYED/xbt_dm_imos_conversion.py", line 442, in <module>
    path = process_xbt_file(NETCDF_FILE_PATH, vargs.output_folder)
  File "/Users/cow074/xbt_processing/data-services/SOOP/SOOP_XBT/DELAYED/xbt_dm_imos_conversion.py", line 405, in process_xbt_file
    gatts, data, annex = parse_edited_nc(xbt_file_path)
  File "/Users/cow074/xbt_processing/data-services/SOOP/SOOP_XBT/DELAYED/xbt_dm_imos_conversion.py", line 177, in parse_edited_nc
    depth_press_flag = np.ma.masked_array([int(a) for a in invalid_to_ma_array(depth_press_flag, fillvalue=0)])  # replace masked values to 0 for IMOS IODE flags
  File "/Users/cow074/xbt_processing/data-services/SOOP/SOOP_XBT/DELAYED/xbt_dm_imos_conversion.py", line 177, in <listcomp>
    depth_press_flag = np.ma.masked_array([int(a) for a in invalid_to_ma_array(depth_press_flag, fillvalue=0)])  # replace masked values to 0 for IMOS IODE flags
  File "/Users/cow074/opt/anaconda3/envs/data-services_3.5/lib/python3.5/site-packages/numpy/ma/core.py", line 4312, in __int__
    raise MaskError('Cannot convert masked element to a Python int.')
numpy.ma.core.MaskError: Cannot convert masked element to a Python int.

**Comment by lbesnard** [comment]
@BecCowley 
I did a small modification on the xbt filename . Can you check it does what you want?

**Comment by lbesnard** [comment]
> @lbesnard, I had an error when trying to convert a file that has a QC of 2 on the DEPTH values. I will email you the file. We need to make sure depth flags are also transferred to the IMOS format files.

thanks Im looking at it

**Comment by BecCowley** [comment]
> @BecCowley
> I did a small modification on the xbt filename . Can you check it does what you want?

@lbesnard, the filename looks good now, thanks.

**Comment by lbesnard** [comment]
@BecCowley 
just fixed the issues with the depth you found. I added some unittests

**Comment by BecCowley** [comment]
@lbesnard, thanks it works.

**Comment by lbesnard** [comment]
@BecCowley if you don't find any other issues next week, I'll merge this to master if you re happy with this

**Comment by BecCowley** [comment]
@lbesnard, I've just run it over the BOM 2019 IX01 and the latest 2020 IX28 files. I have submitted them.
I'll let users know they will be available soon and we'll see if there is any feedback. I think you can go ahead and commit.

**Pull request merged**
