### PR TITLE
SOOP XBT fix NetCDF attribute failing CF

### PR DESCRIPTION
**Pull request by lbesnard**
Fix various issues such as ```Unidentifiable feature for variable``` ...

### CODE REVIEW

**Comment by lbesnard** [comment]
still issues with local instance of cc
```
§3.1 Units
* units for TEMP, "Celcius" are not recognized by UDUNITS
* units for variable TEMP must be convertible to K currently they are Celcius
* units for TEMP_RAW, "Celcius" are not recognized by UDUNITS

§9.1 Features and feature types
* Unidentifiable feature for variable HISTORY_PREVIOUS_VALUE
```

The udunits issues should be fine. However HISTORY_PREVIOUS_VALUE variable is a complicated one as it is used for QC for different variables. It should be featureless. Need to investigate why CC complains:


```
dimensions:
        DEPTH_RAW = 1747 ;
        DEPTH = 1747 ;
        N_HISTORY = UNLIMITED ; // (8 currently)
variables:
        float HISTORY_PREVIOUS_VALUE(N_HISTORY) ;
                HISTORY_PREVIOUS_VALUE:long_name = "Parameter previous value before action" ;
                HISTORY_PREVIOUS_VALUE:units = "1" ;
// global attributes:
                :featureType = "profile" ;
```

**Comment by mhidas** [comment]
> * units for TEMP, "Celcius" are not recognized by UDUNITS

Try "Celsius"

> Unidentifiable feature for variable HISTORY_PREVIOUS_VALUE

Unfortunately this might be another case of this checker bug: https://github.com/ioos/compliance-checker/issues/850
If you show me an example of a complete file, I _might_ be able to help find a workaround.

**Comment by lbesnard** [comment]
> Try "Celsius"

!! thanks :)

**Comment by lbesnard** [comment]
> > Unidentifiable feature for variable HISTORY_PREVIOUS_VALUE
> 
> Unfortunately this might be another case of this checker bug: [ioos/compliance-checker#850](https://github.com/ioos/compliance-checker/issues/850)
> If you show me an example of a complete file, I _might_ be able to help find a workaround.

I fixed it by adding the axis  and positive attribute

**Comment by lbesnard** [comment]
@BecCowley The files I received were failing our various checks and weren't CF compliant. Could you have a look at this PR and make sure you're happy with it? 
I will have to delete the files you sent prior to you reprocessing them and sending them back.

**Comment by BecCowley** [comment]
@lbesnard, thanks for fixing these  issues. The fixes look OK to me.

**Comment by lbesnard** [comment]
cool, I'll merge and chat back to you via email

**Pull request merged**
