### PR TITLE
Turn on end-of-line normalization for PARAMETERS_MAPPING csv tables 

### PR DESCRIPTION
**Pull request by mhidas**
…and normalize parameters_mapping.csv (which had CRLF terminators). None of of the text has been changed!

See https://git-scm.com/docs/gitattributes#_text

### CODE REVIEW

**Comment by mhidas** [comment]
Note, if you need to have CRLF (Windows-style) line endings in your working directory, you can set `core.autocrlf` in your git config (see https://git-scm.com/docs/gitattributes#_end_of_line_conversion)

**Comment by ana-berger** [comment]
@mhidas can we merge this? then I think the plankton products metadata headers task will be concluded

**Comment by mhidas** [comment]
> can we merge this?

Yes, you can! Unless there are any @bpasquer or @evacougnon  have any concerns?

**Comment by ana-berger** [comment]
I will merge it then. And then also [#1003](ana-berger-patch-1), if the conflicts get resolved

**Pull request merged**
