### PR TITLE
 ANFOG_DM :fix issue with TIME attributes

### PR DESCRIPTION
**Pull request by bpasquer**
- replace call to awk by gawk in netcdf-utils.sh for improved performance
- fix issue with TIME variable and gatt time_coverage_start/end discrepancy

### CODE REVIEW

**Comment by bpasquer** [comment]
@lbesnard  i tested successfully the pipeline with function using gawk 
could you review and merge the changes . I'll test again in rc tomorrow. Thanks

**Comment by mhidas** [comment]
Looks good to me.

**Comment by mhidas** [comment]
@bpasquer Oops, it looks like `gawk` does not exist on 10-aws-syd or 14-nsp-mel.

**Comment by bpasquer** [comment]
Loz was supposed to install it
On 5 Apr 2016, at 5:47 PM, Marty Hidas <notifications@github.com<mailto:notifications@github.com>> wrote:


@bpasquer<https://github.com/bpasquer> Oops, it looks like gawk does not exist on 10-aws-syd or 14-nsp-mel.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/aodn/data-services/pull/407#issuecomment-205705623>

Dr. Benedicte Pasquer
Project Officer, e-Marine Information Infrastructure, IMOS
Monday - Friday 9am -3pm
University of Tasmania, Private Bag 110, Hobart, Tasmania, 7001, Australia
Ph: +61 3 6226 1927















University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by lbesnard** [comment]
yeap, not installed, it's breaking the unittests

**Comment by mhidas** [comment]
@bpasquer @lbesnard `gawk` is now on 14-nsp-mel and ready for testing.

**Comment by bpasquer** [comment]
thanks @mhidas ,i'll run some testing

**Comment by bpasquer** [comment]
testing went alright for me. Good to  be deployed to prod

**Pull request merged**
