### PR TITLE
Add watch/handler files for ACORN_DM processing

### PR DESCRIPTION
**Pull request by lwgordonimos**
WIP: do not merge until complete!

### CODE REVIEW

**Comment by ggalibert** [comment]
At terms, when this is deployed and working, we will want to update the ACORN incoming handler's regex so that it only deals with FV00 (RT) files.

**Comment by ggalibert** [comment]
Since there's only a change in the regex for each incoming handler, there might be a more elegant way of doing this rather that duplicating the incoming handler's code in both ACORN and ACORN_DM BASH directories.

**Comment by lwgordonimos** [comment]
@ggalibert looks reasonable to me. When you're around next, we can merge and deploy to RC to complete testing and then arrange for production and notifying the facility.

**Comment by ggalibert** [comment]
A bit weird this file 'File not handled'... Not sure where that comes from.

**Comment by ggalibert** [comment]
This kind of error already exists in production and is not limited to ACORN.

**Pull request merged**
