### PR TITLE
create CARS pipeline

### PR DESCRIPTION
**Pull request by lbesnard**

### CODE REVIEW

**Comment by lbesnard** [comment]
@smancini @jonescc @ggalibert 
This will create a $INCOMING/CSIRO/CARS folder. 

to do
``` bash
cd $INCOMING/CSIRO/CARS
wget http://thredds.aodn.org.au/thredds/fileServer/CSIRO/Climatology/CARS/2009/eMII-product/CARS2009_Australia_weekly.nc
wget http://thredds.aodn.org.au/thredds/fileServer/CSIRO/Climatology/CARS/2009/eMII-product/CARS2009_World_monthly.nc

# Not important to do right now, has to be done once transition to generic harvester has worked
po_s3_del CARS/2009/eMII-product/CARS2009_Australia_weekly.nc 
po_s3_del CSIRO/Climatology/CARS/2009/eMII-product/CARS2009_World_monthly.nc
```

The products will be in ```CSIRO/Climatology/CARS/2009/AODN-product```

**Comment by jonescc** [comment]
@lbesnard - causing issues with inotify_po on 10-aws-syd

Traceback (most recent call last):
  File "/mnt/ebs/data-services/celeryd/inotify.py", line 29, in <module>
    for f in listFiles(dir):
  File "/mnt/ebs/data-services/celeryd/inotify.py", line 19, in listFiles
    return [os.path.join(path, f) for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))]
OSError: [Errno 2] No such file or directory: '/mnt/ebs/incoming/CSIRO/CARS'

**Comment by lbesnard** [comment]
@jonescc Do you know what was the issue ? It was working fine on my po

**Comment by jonescc** [comment]
The /mnt/ebs/incoming/CSIRO/CARS directory did not get created automatically by chef.  @lwgordonimos did some investigation after we reverted this and found that automatic creation of the incoming directory has been turned off for some reason.  We were unsure whether we needed to create it manually (this doesn't seem right).

Since we did not know hat was meant to happen here or how to test whether we the ppleline was working we erred on the side of caution and reverted the change until we could discuss it with you.

**Comment by lbesnard** [comment]
sounds good. I noticed it on Wednesday eve on NSP14. I sent an email to @lwgordonimos as it looked suspicious that the directory didn't get created.

**Comment by jonescc** [comment]
So sounds like you were expecting it to get created automatically as well.  In which case we can check commit messages for the changes and perhaps re-enable/test.

**Comment by lbesnard** [comment]
> So sounds like you were expecting it to get created automatically as well.

definitely, that's how it used to work in the past

**Comment by lwgordonimos** [comment]
@lbesnard @jonescc The relevant item appears to be: 

https://github.com/aodn/chef/blob/master/cookbooks/imos_po/attributes/data_services.rb#L93

This commit (below) looks to have added that option, but it was added as always false. Notably, the PO data bag looks to set it to true, which explains the discrepancy with testing. Will test setting to to true on a vagrant build of 10-aws-syd, and look to getting it enabled in the real thing.

https://github.com/aodn/chef/commit/5682ba458fbc656bc80c2e2a959c44c2e24b676b

**Comment by lbesnard** [comment]
@lwgordonimos what is the plan for this issue ? can we re revert the commit ?

**Comment by lwgordonimos** [comment]
@lbesnard will test turning on auto-creation in vagrant on 14, and we'll see how it behaves

**Pull request merged**
